name: ci

env:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  CTEST_NO_TESTS_ACTION: error
  CMAKE_BUILD_PARALLEL_LEVEL: 4
  CTEST_PARALLEL_LEVEL: 0

on:
  push:
    paths:
      - "**.c"
      - "**.f"
      - "**.F"
      - "**.f90"
      - "**.F90"
      - "**.cmake"
      - "**.txt"
      - ".github/workflows/ci.yml"
      - "!scripts/*"

jobs:

  core:
    timeout-minutes: 15

    strategy:
      matrix:
        scotch: [false]
        metis: [false]
        lapack_vendor: [""]
        img: [ {os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin},
               {os: macos-latest, cmd: brew install open-mpi}
        ]
        include:
          - scotch: true
            img: {os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin}
          - metis: true
            img: {os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin}
          - lapack_vendor: "OpenBLAS"
            img: {os: ubuntu-latest, cmd: sudo apt update && sudo apt install --no-install-recommends libopenmpi-dev openmpi-bin libopenblas-dev}

    runs-on: ${{ matrix.img.os }}

    env:
      FC: gfortran-12

    steps:

    - name: Install prereqs
      run: ${{ matrix.img.cmd }}

    - uses: actions/checkout@v4

    - name: Build METIS
      if: ${{ matrix.metis }}
      run: cmake -P scripts/build_metis.cmake

    - name: Build scotch
      if: ${{ matrix.scotch }}
      run: cmake -P scripts/build_scotch.cmake

    - name: configure
      run: >-
        cmake
        --preset default
        -Dscotch:BOOL=${{ matrix.scotch }}
        -Dmetis:BOOL=${{ matrix.metis }}
        -DLAPACK_VENDOR=${{ matrix.lapack_vendor }}

    - name: build, test release
      run: cmake --workflow --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: cmake -S example -B example/build

    - name: build example
      run: cmake --build example/build

    - name: test example
      run: ctest --test-dir example/build -V

    - name: Scotch example
      if: ${{ matrix.scotch }}
      run: |
        cmake -S example/scotch -Bexample/scotch/build
        cmake --build example/scotch/build
        ctest --test-dir example/scotch/build

    - name: print config log
      if: ${{ failure() && matrix.scotch }}
      run: |
        cat example/scotch/build/CMakeFiles/CMakeConfigureLog.yaml

    - name: METIS example
      if: ${{ matrix.metis }}
      run: |
        cmake -S example/metis -Bexample/metis/build
        cmake --build example/metis/build
        ctest --test-dir example/metis/build

    - name: print config log
      if: ${{ failure() && matrix.metis }}
      run: |
        cat example/metis/build/CMakeFiles/CMakeConfigureLog.yaml
