name: ci_windows

env:
  CMAKE_BUILD_TYPE: Release

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  windows:
    runs-on: windows-latest
    timeout-minutes: 15
    env:
      CMAKE_GENERATOR: MinGW Makefiles

    strategy:
      matrix:
        shared: [true, false]

    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-lapack

    - name: Put MSYS2_MinGW64 on PATH
      # this is because GNU Patch doesn't work from MSYS2 shell
      run: echo "D:/a/_temp/msys64/mingw64/bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

    - uses: actions/checkout@v2

    - run: cmake -B build -Darith=d -Dparallel:BOOL=false -DCMAKE_INSTALL_PREFIX=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: cmake -S example -B example/build -Dparallel:BOOL=false -DCMAKE_PREFIX_PATH=${{ runner.temp }} -DBUILD_SHARED_LIBS:BOOL=${{ matrix.shared }}
    - name: build example
      run: cmake --build example/build --parallel || cmake --build example/build -v
    - name: test example
      run: ctest --test-dir example/build -V
