name: ci_windows

env:
  CMAKE_BUILD_TYPE: Release
  CMAKE_GENERATOR: Ninja

on:
  push:
    paths:
      - "**.cmake"
      - "**/CMakeLists.txt"
      - ".github/workflows/ci_windows.yml"


jobs:

  windows:
    runs-on: windows-latest
    timeout-minutes: 15

    defaults:
      run:
        shell: msys2 {0}
    steps:
    - uses: msys2/setup-msys2@v2
      with:
        update: true
        install: >-
          git
          mingw-w64-x86_64-cmake
          mingw-w64-x86_64-ninja
          mingw-w64-x86_64-gcc-fortran
          mingw-w64-x86_64-lapack
    # cmake install needed because of default to msys2 shell

    - uses: actions/checkout@v2

    - run: cmake -B build -Darith=d -Dparallel:BOOL=false --install-prefix=${{ runner.temp }}
    - run: cmake --build build --parallel
    - run: ctest --test-dir build --preset default

    - name: install package
      run: cmake --install build

    - name: configure example
      run: cmake -S examples -B examples/build -DCMAKE_PREFIX_PATH=${{ runner.temp }} -Dparallel:BOOL=false
    - name: build example
      run: cmake --build examples/build || cmake --build examples/build -v
    - name: test example
      run: ctest --test-dir examples/build -V
